package InterfaceGUI;

import Strategy.Easy;
import Strategy.Hard;
import Strategy.IStrategy;
import Strategy.Medium;
import World.CircusOfPlates;
import javax.swing.JFrame;

/**
 *
 * @author abdel
 */
public class Difficulty extends javax.swing.JFrame implements node{
    private node p;
//    public static int flag;
    private IStrategy strategy;
    
    /**
     * Creates new form Difficulty
     */
    public Difficulty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hard = new javax.swing.JButton();
        Easy = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        Medium = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hard.setBackground(new java.awt.Color(0, 0, 0));
        Hard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Hard.setForeground(new java.awt.Color(255, 255, 102));
        Hard.setText("HARD");
        Hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardActionPerformed(evt);
            }
        });
        getContentPane().add(Hard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 240, 50));

        Easy.setBackground(new java.awt.Color(0, 0, 0));
        Easy.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Easy.setForeground(new java.awt.Color(255, 255, 102));
        Easy.setText("EASY");
        Easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyActionPerformed(evt);
            }
        });
        getContentPane().add(Easy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 240, 50));

        Return.setBackground(new java.awt.Color(0, 0, 0));
        Return.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Return.setForeground(new java.awt.Color(255, 255, 102));
        Return.setText("RETURN");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 240, 50));

        Medium.setBackground(new java.awt.Color(0, 0, 0));
        Medium.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Medium.setForeground(new java.awt.Color(255, 255, 102));
        Medium.setText("MEDIUM");
        Medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumActionPerformed(evt);
            }
        });
        getContentPane().add(Medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Difficulty.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyActionPerformed
        this.dispose();
        this.strategy = new Easy();
        GameController gameController = new GameController(() -> new CircusOfPlates(1200, 750,strategy));
        gameController.start();
           
    }//GEN-LAST:event_EasyActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        this.dispose();
        ((JFrame) getParentNode()).setVisible(true);  
        ((JFrame) getParentNode()).setAlwaysOnTop(true);
    }//GEN-LAST:event_ReturnActionPerformed

    private void MediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumActionPerformed
        this.dispose();
        this.strategy = new Medium();
        GameController gameController = new GameController(() -> new CircusOfPlates(1200, 750,strategy));
        gameController.start();
        
    }//GEN-LAST:event_MediumActionPerformed

    private void HardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardActionPerformed
        this.dispose();
        this.strategy = new Hard();
        GameController gameController = new GameController(() -> new CircusOfPlates(1200, 750,strategy));
        gameController.start();
    }//GEN-LAST:event_HardActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Easy;
    private javax.swing.JButton Hard;
    private javax.swing.JButton Medium;
    private javax.swing.JButton Return;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public node getParentNode() {
        return p;
    }

    @Override
    public void setParentNode(node node) {
        this.p = node;
    }
}
